language: go

go:
  - "1.10.x"

stages:
  - name: tests
  - name: release
    if: tag IS present

jobs:
  include:
    - name: "Unit tests"
      stage: test
      script: make test
    - name: "Integration test: simple proxy"
      before_install:
        - go get -u gopkg.in/alecthomas/gometalinter.v2
        - gometalinter.v2 --install
      before_script:
        - go build ./cmd/gometalint-proxy
      script:
        - ./gometalint-proxy ./_fixtures 2>&1 | tee -a proxy.log | grep "15 issues found"
      after_failure:
        - cat proxy.log
        - gometalinter.v2 --disable-all --enable=dupl --enable=gas --enable=gofmt --enable=goimports --enable=lll --enable=misspell ./_fixtures
    - name: "Generated code"
      before_install:
        - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      script:
        - dep ensure -v
        - make no-changes-in-commit
        - make protogen
        - make no-changes-in-commit
        - make build
        - make no-changes-in-commit
    - name: "Push image to Docker Hub"
      stage: release
      script:
        - PKG_OS=linux make build
        - DOCKER_PUSH_LATEST=true make docker-push

cache:
  directories:
    - $HOME/protoc